/* tslint:disable */
/* eslint-disable */
/**
 * IP geolocation API
 * Abstract IP geolocation API allows developers to retrieve the region, country and city behind any IP worldwide. The API covers the geolocation of IPv4 and IPv6 addresses in 180+ countries worldwide. Extra information can be retrieved like the currency, flag or language associated to an IP.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200Flag
 */
export interface InlineResponse200Flag {

    /**
     * @type {string}
     * @memberof InlineResponse200Flag
     */
    emoji?: string;

    /**
     * @type {string}
     * @memberof InlineResponse200Flag
     */
    png?: string;

    /**
     * @type {string}
     * @memberof InlineResponse200Flag
     */
    svg?: string;

    /**
     * @type {string}
     * @memberof InlineResponse200Flag
     */
    unicode?: string;
}
