/* tslint:disable */
/* eslint-disable */
/**
 * IP geolocation API
 * Abstract IP geolocation API allows developers to retrieve the region, country and city behind any IP worldwide. The API covers the geolocation of IPv4 and IPv6 addresses in 180+ countries worldwide. Extra information can be retrieved like the currency, flag or language associated to an IP.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse200Connection } from './inline-response200-connection';
import { InlineResponse200Currency } from './inline-response200-currency';
import { InlineResponse200Flag } from './inline-response200-flag';
import { InlineResponse200Security } from './inline-response200-security';
import { InlineResponse200Timezone } from './inline-response200-timezone';
 /**
 * 
 *
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {

    /**
     * @type {string}
     * @memberof InlineResponse200
     */
    city?: string;

    /**
     * @type {number}
     * @memberof InlineResponse200
     */
    cityGeonameId?: number;

    /**
     * @type {InlineResponse200Connection}
     * @memberof InlineResponse200
     */
    connection?: InlineResponse200Connection;

    /**
     * @type {string}
     * @memberof InlineResponse200
     */
    continent?: string;

    /**
     * @type {string}
     * @memberof InlineResponse200
     */
    continentCode?: string;

    /**
     * @type {number}
     * @memberof InlineResponse200
     */
    continentGeonameId?: number;

    /**
     * @type {string}
     * @memberof InlineResponse200
     */
    country?: string;

    /**
     * @type {string}
     * @memberof InlineResponse200
     */
    countryCode?: string;

    /**
     * @type {number}
     * @memberof InlineResponse200
     */
    countryGeonameId?: number;

    /**
     * @type {boolean}
     * @memberof InlineResponse200
     */
    countryIsEu?: boolean;

    /**
     * @type {InlineResponse200Currency}
     * @memberof InlineResponse200
     */
    currency?: InlineResponse200Currency;

    /**
     * @type {InlineResponse200Flag}
     * @memberof InlineResponse200
     */
    flag?: InlineResponse200Flag;

    /**
     * @type {string}
     * @memberof InlineResponse200
     */
    ipAddress?: string;

    /**
     * @type {number}
     * @memberof InlineResponse200
     */
    latitude?: number;

    /**
     * @type {number}
     * @memberof InlineResponse200
     */
    longitude?: number;

    /**
     * @type {string}
     * @memberof InlineResponse200
     */
    postalCode?: string;

    /**
     * @type {string}
     * @memberof InlineResponse200
     */
    region?: string;

    /**
     * @type {number}
     * @memberof InlineResponse200
     */
    regionGeonameId?: number;

    /**
     * @type {string}
     * @memberof InlineResponse200
     */
    regionIsoCode?: string;

    /**
     * @type {InlineResponse200Security}
     * @memberof InlineResponse200
     */
    security?: InlineResponse200Security;

    /**
     * @type {InlineResponse200Timezone}
     * @memberof InlineResponse200
     */
    timezone?: InlineResponse200Timezone;
}
