/* tslint:disable */
/* eslint-disable */
/**
 * Todo API
 * A simple Todo API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Todo
 */
export interface Todo {

    /**
     * The unique identifier of the todo
     *
     * @type {number}
     * @memberof Todo
     */
    id: number;

    /**
     * The title of the todo
     *
     * @type {string}
     * @memberof Todo
     */
    title: string;
}
